import csv
import json
from decimal import Decimal, InvalidOperation
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.utils.text import slugify

from app.models import Category, Product


class Command(BaseCommand):
    help = "Import normalized products.csv generated by ai-service."

    def add_arguments(self, parser):
        parser.add_argument("path")
        parser.add_argument("--limit", type=int, default=5000)

    def handle(self, *args, **options):
        path = Path(options["path"])
        if not path.exists():
            raise CommandError(f"Catalog file does not exist: {path}")

        imported = 0
        with path.open("r", encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                if imported >= options["limit"]:
                    break
                source = row.get("source", "").strip()
                external_id = row.get("external_id", "").strip()
                title = row.get("title", "").strip()
                if not source or not external_id or not title:
                    continue
                category_name = row.get("category", "").strip() or row.get("domain", "General")
                category, _ = Category.objects.get_or_create(
                    slug=slugify(category_name)[:120] or "general",
                    defaults={"name": category_name[:100]},
                )
                try:
                    price = Decimal(row.get("price") or "0")
                except InvalidOperation:
                    price = Decimal("0")
                metadata = {}
                if row.get("metadata"):
                    try:
                        metadata = json.loads(row["metadata"])
                    except json.JSONDecodeError:
                        metadata = {"raw": row["metadata"]}
                Product.objects.update_or_create(
                    source=source,
                    external_id=external_id,
                    defaults={
                        "title": title[:255],
                        "author": row.get("creator_or_brand", "")[:255],
                        "creator_or_brand": row.get("creator_or_brand", "")[:255],
                        "description": row.get("description", ""),
                        "price": price,
                        "stock": int(float(row.get("stock") or 100)),
                        "category": category,
                        "domain": row.get("domain", "general"),
                        "image_url": row.get("image_url", "")[:1000],
                        "metadata": metadata,
                        "is_active": True,
                    },
                )
                imported += 1
        self.stdout.write(self.style.SUCCESS(f"Imported or updated {imported} products"))
