from django.urls import path
from .views import (
    home,
    register_page,
    login_page,
    logout_view,
    product_list,
    product_detail,
    rate_product,
    view_cart,
    my_cart,
    add_to_cart,
    remove_cart_item,
    update_cart_item,
    checkout,
    place_order,
    staff_products,
    staff_edit_product,
    staff_delete_product,
    order_history,
    profile_page,
    wishlist_page,
    toggle_wishlist,
    api_customers,
    api_auth_register,
    api_auth_login,
    api_products,
    api_product_detail,
    api_categories,
    api_product_search,
    api_cart_items,
    api_cart_item_detail,
    api_cart_detail,
    api_orders,
    api_order_detail,
    api_ratings,
    api_ratings_list,
    api_behavior_score,
    api_behavior_recommend,
    api_graph_recommend,
    api_chat_advice,
    health,
)

urlpatterns = [
    # Web interface (HTML)
    path('', home, name='home'),
    path('auth/register/', register_page, name='register_page'),
    path('auth/login/', login_page, name='login_page'),
    path('auth/logout/', logout_view, name='logout_view'),

    path('products/', product_list, name='product_list'),
    path('products/<int:product_id>/', product_detail, name='product_detail'),
    path('products/<int:product_id>/rate/', rate_product, name='rate_product'),
    path('cart/<int:customer_id>/', view_cart, name='view_cart'),
    path('my-cart/', my_cart, name='my_cart'),
    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove-cart-item/<int:item_id>/', remove_cart_item, name='remove_cart_item'),
    path('update-cart-item/<int:item_id>/', update_cart_item, name='update_cart_item'),
    path('checkout/', checkout, name='checkout'),
    path('place-order/', place_order, name='place_order'),
    path('orders/', order_history, name='order_history'),

    # Profile & Wishlist
    path('profile/', profile_page, name='profile_page'),
    path('wishlist/', wishlist_page, name='wishlist_page'),
    path('wishlist/toggle/<int:product_id>/', toggle_wishlist, name='toggle_wishlist'),

    path('staff/products/', staff_products, name='staff_products'),
    path('staff/products/edit/<int:product_id>/', staff_edit_product, name='staff_edit_product'),
    path('staff/products/delete/<int:product_id>/', staff_delete_product, name='staff_delete_product'),

    # JSON API qua Gateway
    path('api/auth/register/', api_auth_register, name='api_auth_register'),
    path('api/auth/login/', api_auth_login, name='api_auth_login'),
    path('api/customers/', api_customers, name='api_customers'),
    path('api/products/', api_products, name='api_products'),
    path('api/products/<int:pk>/', api_product_detail, name='api_product_detail'),
    path('api/products/search/', api_product_search, name='api_product_search'),
    path('api/categories/', api_categories, name='api_categories'),

    path('api/cart-items/', api_cart_items, name='api_cart_items'),
    path('api/cart-items/<int:pk>/', api_cart_item_detail, name='api_cart_item_detail'),
    path('api/carts/<int:customer_id>/', api_cart_detail, name='api_cart_detail'),

    path('api/orders/', api_orders, name='api_orders'),
    path('api/orders/<int:pk>/', api_order_detail, name='api_order_detail'),

    path('api/ratings/', api_ratings, name='api_ratings'),
    path('api/ratings/list/', api_ratings_list, name='api_ratings_list'),
    path('api/behavior/score/', api_behavior_score, name='api_behavior_score'),
    path('api/behavior/recommend-products/', api_behavior_recommend, name='api_behavior_recommend'),
    path('api/graph/recommendations/', api_graph_recommend, name='api_graph_recommend'),
    path('api/chat/advice/', api_chat_advice, name='api_chat_advice'),
    path('health/', health, name='health'),
]
